{% set name = "pytest-env" %}
{% set version = "1.6.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ac02d6fba16af54d61e311dd70a3c61024a4e966881ea844affc3c8f0bf207d3

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.28
    - hatch-vcs >=0.5
  run:
    - python >={{ python_min }}
    - pytest >=9.0.2
    - python-dotenv >=1.2.1
    - tomli >=2.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_env.plugin
  commands:
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-env
  dev_url: https://github.com/pytest-dev/pytest-env
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: This is a pytest plugin that enables you to set environment variables in a pytest.ini or pyproject.toml file.

extra:
  recipe-maintainers:
    - nicoddemus
