{% set name = "pytest-env" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fcd7dc23bb71efd3d35632bde1bbe5ee8c8dc4489d6617fb010674880d96216b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.8
    - hatchling >=1.8
    - hatch-vcs >=0.3
  run:
    - python >=3.8
    - pytest >=7.4.2
    - tomli >=2.0.1

test:
  imports:
    - pytest_env.plugin
  commands:
    - pytest --help

about:
  home: https://github.com/pytest-dev/pytest-env
  dev_url: https://github.com/pytest-dev/pytest-env
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: This is a pytest plugin that enables you to set environment variables in a pytest.ini or pyproject.toml file.

extra:
  recipe-maintainers:
    - nicoddemus
